name: ci

on:
  pull_request:
<<<<<<< HEAD
  #push:
=======
>>>>>>> 9802e06b247dd94aaf7d4448daac3ce2aa4c066d

jobs:
  build:
    runs-on: ubuntu-latest

    env:
<<<<<<< HEAD
      github-token: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
=======
      github-token: ${{secrets.GITHUB_TOKEN}}
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
>>>>>>> 9802e06b247dd94aaf7d4448daac3ce2aa4c066d

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Node
      uses: actions/setup-node@v1
      with:
        node-version: 12

    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      run: echo "::set-output name=dir::$(yarn cache dir)"

    - uses: actions/cache@v1
      id: yarn-cache
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - name: Install dependencies
      run: yarn install

    - name: Check tests
      run: yarn test

    - name: Check linting
      run: yarn lint

    - name: Check commit message
      uses: wagoid/commitlint-github-action@v1

<<<<<<< HEAD
    - name: Coveralls GitHub Action
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
=======
    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
>>>>>>> 9802e06b247dd94aaf7d4448daac3ce2aa4c066d
        path-to-lcov: ./coverage/lcov.info
